### ISSUE TITLE
Compiled firmware when new updates are made?

### ISSUE THREAD

**Issue by Helder1981** [borti4938/n64rgb#9]
I wouldn't bother requesting this but I followed the instructions on the firmware folder to build the firmware but I get errors half way through and the whole operation halts. 

I am very unfamiliar with the software to know how to fix it so I'd like to request new firmware changes you make to be compiled and uploaded to the output folder. Thank you 

If maybe someone has a good guide to follow to do this that would be great and save you from doing any extra work, there seems to be alot of information in this github and conflicts with the readme files and PDF files. It would be nice if the proper information was all in one place and to get rid of the old or wrong information. Again thank you for the work you are constantly doing on this.

**Comment by borti4938** [comment]
> I get errors half way through and the whole operation halts.  

It would be helpful if you write where you stuck at. Otherwise I cannot help.

> I'd like to request new firmware changes you make to be compiled

Sometimes I wait with new firmware files to be uploaded. This may have several reasons. Among others:

- There are just minor changes without any new features.
- I don't feel comfortable enough to upload new fw files if certain parts are changed like the timing description. In this case I wait for some more testings from my side and also from friends.

This time its the second cause and I accidently pushed changes to Github. Firmware will be uploaded in near future.

> there seems to be alot of information in this github and conflicts with the readme files and PDF files.

Also here it would be very helpful if you write where conflicts are. Keeping documentation up to date is very time consuming over the time of such a big DIY project for just a single person.
Sometimes I feel it would be better to have virtually zero documentation like other commercial products.

> It would be nice if the proper information was all in one place and to get rid of the old or wrong information.

The spreaded information is somehow a product of how the project grew up. I don't have the motivation to change that. 
Feel free to change it and make a pull request, though ;)

**Comment by borti4938** [comment]
Firmware files are now up to date. I also updated the PDF file (mainly menu description).
Actually I don't know where wrong information in the documents. But it's sometimes very difficult to find for myself without useful feedback.
So I close for now the issue
